FROM ouankou/rds:archer

USER rds
RUN git clone https://github.com/ouankou/rds-archer.git
RUN git clone https://github.com/World-Worst-Detector/dataracebench.git && \
    rm -rf /home/rds/dataracebench/micro-benchmarks/* && \
    rm -rf /home/rds/dataracebench/results/*

COPY ["start.sh", "/home/rds/"]

ENTRYPOINT /home/rds/start.sh && /bin/bash
